"""add execution events

Revision ID: 372cc8e18b19
Revises: ececb64e3c67
Create Date: 2026-09-19 15:53:40.531722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372cc8e18b19'
down_revision: Union[str, Sequence[str], None] = 'ececb64e3c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['application_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_created_at'), 'execution_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_events_event_type'), 'execution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_execution_events_execution_id'), 'execution_events', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_events_execution_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_event_type'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_created_at'), table_name='execution_events')
    op.drop_table('execution_events')
    # ### end Alembic commands ###
