"""add job requirement uniqueness

Revision ID: 627f207dfc83
Revises: 3ae28bca3633
Create Date: 2026-09-19 11:21:21.573862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627f207dfc83'
down_revision: Union[str, Sequence[str], None] = '3ae28bca3633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_job_requirement_job_requirement', 'job_requirements', ['job_id', 'requirement'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_requirement_job_requirement', 'job_requirements', type_='unique')
    # ### end Alembic commands ###
