"""add application package model

Revision ID: ca555d1a21be
Revises: dec568a7c243
Create Date: 2026-09-11 18:10:14.493145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca555d1a21be'
down_revision: Union[str, Sequence[str], None] = 'dec568a7c243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('tailored_summary', sa.Text(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('key_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('application_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unsupported_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_packages_application_id'), 'application_packages', ['application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_packages_application_id'), table_name='application_packages')
    op.drop_table('application_packages')
    # ### end Alembic commands ###
