"""add candidate evidence embeddings

Revision ID: cc0acfc32514
Revises: fae0311ef22e
Create Date: 2026-09-08 10:21:16.748109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'cc0acfc32514'
down_revision: Union[str, Sequence[str], None] = 'fae0311ef22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_evidence",
        sa.Column(
            "embedding",
            Vector(1536),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_evidence', 'embedding')
    # ### end Alembic commands ###
