"""add job requirements table

Revision ID: fae0311ef22e
Revises: 43fc98d621c5
Create Date: 2026-09-07 15:09:24.972237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae0311ef22e'
down_revision: Union[str, Sequence[str], None] = '43fc98d621c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('requirement', sa.String(length=255), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_requirements')
    # ### end Alembic commands ###
