from uuid import UUID

from sqlalchemy.orm import Session

from backend.app.models.resume import Resume
from backend.app.services.candidate_evidence_service import (
    create_candidate_evidence,
    delete_resume_evidence,
)
from backend.app.services.evidence_embedding_service import (
    embed_candidate_evidence,
)
from backend.app.services.gemini_service import (
    generate_structured_resume,
)
from backend.app.services.resume_parser_service import (
    detect_sections,
    extract_resume_text,
)
from backend.app.schemas.candidate_evidence import CandidateEvidenceCreate


def process_resume(
    db: Session,
    candidate_id: UUID,
    file_name: str,
    file_path: str,
) -> dict:
    """
    Process an uploaded resume into structured candidate evidence.

    Pipeline:
    PDF -> text -> sections -> structured resume
    -> candidate evidence -> embeddings
    """

    # 1. Extract raw text from the PDF.
    raw_text = extract_resume_text(file_path)

    if not raw_text:
        raise ValueError("Could not extract any text from the resume.")

    # 2. Detect resume sections.
    sections = detect_sections(raw_text)

    # 3. Convert the sections into structured resume data.
    structured_resume = generate_structured_resume(sections)

    # Remove evidence generated by the previous resume.
    delete_resume_evidence(
        db=db,
        candidate_id=candidate_id,
    )
    
    # 4. Store the latest resume for the candidate.
    resume = (
        db.query(Resume)
        .filter(Resume.candidate_id == candidate_id)
        .first()
    )

    if resume is None:
        resume = Resume(
            candidate_id=candidate_id,
            file_name=file_name,
            file_path=file_path,
            raw_text=raw_text,
        )
        db.add(resume)
    else:
        resume.file_name = file_name
        resume.file_path = file_path
        resume.raw_text = raw_text

    db.commit()
    db.refresh(resume)

    # 5. Convert structured resume information into evidence.
    evidence_records = []

    for skill in structured_resume.skills:
        evidence_records.append(
            CandidateEvidenceCreate(
                candidate_id=candidate_id,
                category="skill",
                title=skill,
                content=f"Candidate has the skill: {skill}.",
                source="resume",
            )
        )

    for project in structured_resume.projects:
        technologies = ", ".join(project.technologies)

        content = project.description or project.name

        if technologies:
            content += f" Technologies: {technologies}."

        evidence_records.append(
            CandidateEvidenceCreate(
                candidate_id=candidate_id,
                category="project",
                title=project.name,
                content=content,
                source="resume",
            )
        )

    for experience in structured_resume.experience:
        content = experience.description or ""

        if experience.technologies:
            technologies = ", ".join(
                experience.technologies
            )
            content += f" Technologies: {technologies}."

        title = (
            f"{experience.role or 'Experience'} "
            f"at {experience.company or 'Unknown company'}"
        )

        evidence_records.append(
            CandidateEvidenceCreate(
                candidate_id=candidate_id,
                category="experience",
                title=title,
                content=content.strip() or title,
                source="resume",
            )
        )

    for education in structured_resume.education:
        title = education.institution or "Education"

        content_parts = [
            education.degree,
            education.field_of_study,
            education.dates,
            education.grade,
        ]

        content = " | ".join(
            part for part in content_parts if part
        )

        evidence_records.append(
            CandidateEvidenceCreate(
                candidate_id=candidate_id,
                category="education",
                title=title,
                content=content or title,
                source="resume",
            )
        )

    for certification in structured_resume.certifications:
        content_parts = [
            certification.name,
            certification.issuer,
            certification.date,
        ]

        content = " | ".join(
            part for part in content_parts if part
        )

        evidence_records.append(
            CandidateEvidenceCreate(
                candidate_id=candidate_id,
                category="certification",
                title=certification.name,
                content=content,
                source="resume",
            )
        )

    for achievement in structured_resume.achievements:
        evidence_records.append(
            CandidateEvidenceCreate(
                candidate_id=candidate_id,
                category="achievement",
                title="Resume Achievement",
                content=achievement,
                source="resume",
            )
        )

    if structured_resume.summary:
        evidence_records.append(
            CandidateEvidenceCreate(
                candidate_id=candidate_id,
                category="summary",
                title="Professional Summary",
                content=structured_resume.summary,
                source="resume",
            )
        )

    # 6. Store evidence.
    for evidence_data in evidence_records:
        create_candidate_evidence(
            db=db,
            evidence_data=evidence_data,
        )

    # 7. Generate vector embeddings for the evidence.
    embedded_count = embed_candidate_evidence(
        db=db,
        candidate_id=candidate_id,
    )

    return {
        "resume_id": str(resume.id),
        "candidate_id": str(candidate_id),
        "sections_detected": list(sections.keys()),
        "evidence_created": len(evidence_records),
        "embeddings_created": embedded_count,
        "structured_resume": structured_resume.model_dump(),
    }